grails-app/domain/project/time/management/TaskStatus.groovy
package project.time.management

class TaskStatus {

    String title
    String body
    Long number
    Date dateCreated
    Date lastUpdated

    static constraints = {
    }
    String toString(){
        return title
    }

    public static final String NEED_WORK_ON_IT ="Требует выполнение"
    public static final String IN_WORK ="В обработке"
    public static final String COMPLETE ="Завершенна"
    public static final String IN_WORK_FROZEN ="В обработке - Приостановлена"
    public static final String IN_WORK_DROPPED ="В обработке - Брошенна"
    public static final String FEATURE_NOT_WORK_ON_IT ="Возможная задача "
    public static final String NOT_NEED_ANYMORE ="Не актуальна"

    public static final Long NEED_WORK_ON_IT_NUMBER =0
    public static final Long IN_WORK_NUMBER =1
    public static final Long COMPLETE_NUMBER =2
    public static final Long IN_WORK_FROZEN_NUMBER =3
    public static final Long IN_WORK_DROPPED_NUMBER =4
    public static final Long FEATURE_NOT_WORK_ON_IT_NUMBER =5
    public static final Long NOT_NEED_ANYMORE_NUMBER =6

}

grails-app/controllers/project/time/management/TaskStatusController.groovy
package project.time.management



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TaskStatusController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {

        params.max = Math.min(max ?: 10, 100)
        respond TaskStatus.list(params), model:[taskStatusInstanceCount: TaskStatus.count()]
    }

    def show(TaskStatus taskStatusInstance) {
        respond taskStatusInstance
    }

    def create() {
        respond new TaskStatus(params)
    }

    @Transactional
    def save(TaskStatus taskStatusInstance) {
        if (taskStatusInstance == null) {
            notFound()
            return
        }

        if (taskStatusInstance.hasErrors()) {
            respond taskStatusInstance.errors, view:'create'
            return
        }

        taskStatusInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'taskStatus.label', default: 'TaskStatus'), taskStatusInstance.id])
                redirect taskStatusInstance
            }
            '*' { respond taskStatusInstance, [status: CREATED] }
        }
    }

    def edit(TaskStatus taskStatusInstance) {
        respond taskStatusInstance
    }

    @Transactional
    def update(TaskStatus taskStatusInstance) {
        if (taskStatusInstance == null) {
            notFound()
            return
        }

        if (taskStatusInstance.hasErrors()) {
            respond taskStatusInstance.errors, view:'edit'
            return
        }

        taskStatusInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'TaskStatus.label', default: 'TaskStatus'), taskStatusInstance.id])
                redirect taskStatusInstance
            }
            '*'{ respond taskStatusInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(TaskStatus taskStatusInstance) {

        if (taskStatusInstance == null) {
            notFound()
            return
        }

        taskStatusInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'TaskStatus.label', default: 'TaskStatus'), taskStatusInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'taskStatus.label', default: 'TaskStatus'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/taskStatus/_form.gsp
<%@ page import="project.time.management.TaskStatus" %>



<div class="fieldcontain ${hasErrors(bean: taskStatusInstance, field: 'description', 'error')} required">
	<label for="description">
		<g:message code="taskStatus.description.label" default="Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="description" required="" value="${taskStatusInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: taskStatusInstance, field: 'number', 'error')} required">
	<label for="number">
		<g:message code="taskStatus.number.label" default="Number" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="number" type="number" value="${taskStatusInstance.number}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: taskStatusInstance, field: 'title', 'error')} required">
	<label for="title">
		<g:message code="taskStatus.title.label" default="Title" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="title" required="" value="${taskStatusInstance?.title}"/>

</div>

grails-app/views/taskStatus/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'taskStatus.label', default: 'TaskStatus')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-taskStatus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-taskStatus" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${taskStatusInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${taskStatusInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:taskStatusInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/taskStatus/edit.gsp
<%@ page import="project.time.management.TaskStatus" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'taskStatus.label', default: 'TaskStatus')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-taskStatus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-taskStatus" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${taskStatusInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${taskStatusInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:taskStatusInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${taskStatusInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/taskStatus/index.gsp
<%@ page import="project.time.management.TaskStatus" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'taskStatus.label', default: 'TaskStatus')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-taskStatus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-taskStatus" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="description" title="${message(code: 'taskStatus.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="number" title="${message(code: 'taskStatus.number.label', default: 'Number')}" />
					
						<g:sortableColumn property="title" title="${message(code: 'taskStatus.title.label', default: 'Title')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${taskStatusInstanceList}" status="i" var="taskStatusInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${taskStatusInstance.id}">${fieldValue(bean: taskStatusInstance, field: "description")}</g:link></td>
					
						<td>${fieldValue(bean: taskStatusInstance, field: "number")}</td>
					
						<td>${fieldValue(bean: taskStatusInstance, field: "title")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${taskStatusInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/taskStatus/show.gsp
<%@ page import="project.time.management.TaskStatus" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'taskStatus.label', default: 'TaskStatus')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-taskStatus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-taskStatus" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list taskStatus">
			
				<g:if test="${taskStatusInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="taskStatus.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${taskStatusInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${taskStatusInstance?.number}">
				<li class="fieldcontain">
					<span id="number-label" class="property-label"><g:message code="taskStatus.number.label" default="Number" /></span>
					
						<span class="property-value" aria-labelledby="number-label"><g:fieldValue bean="${taskStatusInstance}" field="number"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${taskStatusInstance?.title}">
				<li class="fieldcontain">
					<span id="title-label" class="property-label"><g:message code="taskStatus.title.label" default="Title" /></span>
					
						<span class="property-value" aria-labelledby="title-label"><g:fieldValue bean="${taskStatusInstance}" field="title"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:taskStatusInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${taskStatusInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>