grails-app/domain/project/time/management/Status.groovy
package project.time.management

import project.time.management.StatusType

class Status {
    Date dateCreated
    Date lastUpdated

    static belongsTo = [statusType: StatusType, project: Project, step: Step]

    static constraints = {
        project nullable: true
        step nullable: true
    }

    public static Status createSaveAndUpdateProjectStatus(Project project, String statusTitle) {
        def statusType = StatusType.findByTitle(statusTitle)
        def status = new Status()
        status.project = project
        status.statusType = statusType
        status.save()
        project.status = status
        project.save()
        return status
    }

    public static Status updateProjectStatus(Project project, String statusTypeTitle) {
        def statusType = StatusType.findByTitle(statusTypeTitle)
        def status = Status.get(project.status.id)
        status.statusType = statusType
        status.save()
        return status
    }


    public static Status createSaveAndUpdateStepStatus(Step step, String statusTitle) {
        def statusType = StatusType.findByTitle(statusTitle)
        def status = new Status()
        status.step = step
        status.statusType = statusType
        status.save()
        step.status = status
        step.save()
        return status
    }

    public static Status updateStepStatus(Step step, String statusTypeTitle) {
        def statusType = StatusType.findByTitle(statusTypeTitle)
        def status = Status.get(step.status.id)
        status.statusType = statusType
        status.save()
        return status
    }

}

grails-app/domain/project/time/management/StatusType.groovy
package project.time.management

class StatusType {

    String title
    Date dateCreated
    Date lastUpdated

    static constraints = {
    }

    public static final String ACTIVE="Активный"
    public static final String FROZEN="Остановлен"
    public static final String COMPLETE="Завершён"

    String  toString(){
    return title
    }
}

grails-app/controllers/project/time/management/StatusController.groovy
package project.time.management



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured



@Secured(["ROLE_ADMIN"])
@Transactional(readOnly = true)
class StatusController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Status.list(params), model:[statusInstanceCount: Status.count()]
    }

    def show(Status statusInstance) {
        respond statusInstance
    }

    def create() {
        respond new Status(params)
    }

    @Transactional
    def save(Status statusInstance) {
        if (statusInstance == null) {
            notFound()
            return
        }

        if (statusInstance.hasErrors()) {
            respond statusInstance.errors, view:'create'
            return
        }

        statusInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'status.label', default: 'Status'), statusInstance.id])
                redirect statusInstance
            }
            '*' { respond statusInstance, [status: CREATED] }
        }
    }

    def edit(Status statusInstance) {
        respond statusInstance
    }

    @Transactional
    def update(Status statusInstance) {
        if (statusInstance == null) {
            notFound()
            return
        }

        if (statusInstance.hasErrors()) {
            respond statusInstance.errors, view:'edit'
            return
        }

        statusInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Status.label', default: 'Status'), statusInstance.id])
                redirect statusInstance
            }
            '*'{ respond statusInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Status statusInstance) {

        if (statusInstance == null) {
            notFound()
            return
        }

        statusInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Status.label', default: 'Status'), statusInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'status.label', default: 'Status'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/status/_form.gsp
<%@ page import="project.time.management.Status" %>



<div class="fieldcontain ${hasErrors(bean: statusInstance, field: 'project', 'error')} ">
	<label for="project">
		<g:message code="status.project.label" default="Project" />
		
	</label>
	<g:select id="project" name="project.id" from="${project.time.management.Project.list()}" optionKey="id" value="${statusInstance?.project?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: statusInstance, field: 'step', 'error')} ">
	<label for="step">
		<g:message code="status.step.label" default="Step" />
		
	</label>
	<g:select id="step" name="step.id" from="${project.time.management.Step.list()}" optionKey="id" value="${statusInstance?.step?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: statusInstance, field: 'statusType', 'error')} required">
	<label for="statusType">
		<g:message code="status.statusType.label" default="Status Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="statusType" name="statusType.id" from="${project.time.management.StatusType.list()}" optionKey="id" required="" value="${statusInstance?.statusType?.id}" class="many-to-one"/>

</div>

grails-app/views/status/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'status.label', default: 'Status')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-status" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-status" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${statusInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${statusInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:statusInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/status/edit.gsp
<%@ page import="project.time.management.Status" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'status.label', default: 'Status')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-status" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-status" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${statusInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${statusInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:statusInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${statusInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/status/index.gsp
<%@ page import="project.time.management.Status" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'status.label', default: 'Status')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-status" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-status" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="status.project.label" default="Project" /></th>
					
						<th><g:message code="status.step.label" default="Step" /></th>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'status.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'status.lastUpdated.label', default: 'Last Updated')}" />
					
						<th><g:message code="status.statusType.label" default="Status Type" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${statusInstanceList}" status="i" var="statusInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${statusInstance.id}">${fieldValue(bean: statusInstance, field: "project")}</g:link></td>
					
						<td>${fieldValue(bean: statusInstance, field: "step")}</td>
					
						<td><g:formatDate date="${statusInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${statusInstance.lastUpdated}" /></td>
					
						<td>${fieldValue(bean: statusInstance, field: "statusType")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${statusInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/status/show.gsp
<%@ page import="project.time.management.Status" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'status.label', default: 'Status')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-status" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-status" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list status">
			
				<g:if test="${statusInstance?.project}">
				<li class="fieldcontain">
					<span id="project-label" class="property-label"><g:message code="status.project.label" default="Project" /></span>
					
						<span class="property-value" aria-labelledby="project-label"><g:link controller="project" action="show" id="${statusInstance?.project?.id}">${statusInstance?.project?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${statusInstance?.step}">
				<li class="fieldcontain">
					<span id="step-label" class="property-label"><g:message code="status.step.label" default="Step" /></span>
					
						<span class="property-value" aria-labelledby="step-label"><g:link controller="step" action="show" id="${statusInstance?.step?.id}">${statusInstance?.step?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${statusInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="status.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${statusInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${statusInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="status.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${statusInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${statusInstance?.statusType}">
				<li class="fieldcontain">
					<span id="statusType-label" class="property-label"><g:message code="status.statusType.label" default="Status Type" /></span>
					
						<span class="property-value" aria-labelledby="statusType-label"><g:link controller="statusType" action="show" id="${statusInstance?.statusType?.id}">${statusInstance?.statusType?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:statusInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${statusInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>